title: 321 Make! facilitator guide to using our paths
hero_image: images/banner.png
description: A guide for facilitators using our 321 Make! paths of projects. 
version: 4
listed: false
copyedit: false
last_tested: "2022-05-09"
steps: 
  - title: Introduction
  - title: Why 321 Make! ?
  - title: What is a path?
  - title: 3 Explore projects
  - title: 2 Design projects
  - title: 1 Invent project
  - title: Make! projects
  - title: What next?
  - title: Reflection
